import { chromium } from 'playwright';
import readline from 'node:readline';
import { existsSync } from 'node:fs';
import dns from 'node:dns/promises';
import net from 'node:net';
let browser,context,page,generation=0;const references=new Map();
function blockedIp(address){
  if(net.isIP(address)===4){const [a,b]=address.split('.').map(Number);return a===0||a===10||a===127||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===192&&b===0)||(a===198&&(b===18||b===19||b===51))||(a===203&&b===0)||(a===100&&b>=64&&b<=127)||a>=224;}
  const value=address.toLowerCase();if(value.startsWith('::ffff:')){const mapped=value.slice(7);if(net.isIP(mapped)===4)return blockedIp(mapped);}return value==='::'||value==='::1'||value.startsWith('fc')||value.startsWith('fd')||value.startsWith('fe8')||value.startsWith('fe9')||value.startsWith('fea')||value.startsWith('feb')||value.startsWith('ff')||value.startsWith('2001:db8');
}
async function publicAddress(value){const url=new URL(value);if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw new Error('Only clean HTTP or HTTPS addresses are allowed');const host=url.hostname.replace(/^\[|\]$/g,'').replace(/\.$/,'').toLowerCase();if(!host||['localhost','localhost.localdomain','ip6-localhost'].includes(host))throw new Error('Local and loopback addresses are not allowed');if(net.isIP(host)){if(blockedIp(host))throw new Error('Private, loopback, or reserved addresses are not allowed');return url.href;}let addresses;try{addresses=(await dns.lookup(host,{all:true,verbatim:true})).map(x=>x.address);}catch{throw new Error('The browser could not resolve the requested host');}if(!addresses.length||addresses.some(blockedIp))throw new Error('The browser blocked a private or reserved network target');return url.href;}
async function connect(){if(page&&!page.isClosed())return;const edge=[`${process.env['ProgramFiles(x86)']||'C:\\Program Files (x86)'}\\Microsoft\\Edge\\Application\\msedge.exe`,`${process.env.ProgramFiles||'C:\\Program Files'}\\Microsoft\\Edge\\Application\\msedge.exe`];const chrome=[`${process.env.ProgramFiles||'C:\\Program Files'}\\Google\\Chrome\\Application\\chrome.exe`,`${process.env['ProgramFiles(x86)']||'C:\\Program Files (x86)'}\\Google\\Chrome\\Application\\chrome.exe`,`${process.env.LOCALAPPDATA||''}\\Google\\Chrome\\Application\\chrome.exe`];const executablePath=[...edge,...chrome].find(existsSync);browser=await chromium.launch({headless:process.env.STONIC_BROWSER_HEADLESS==='1',executablePath});context=await browser.newContext({acceptDownloads:false,viewport:{width:1280,height:800}});await context.route('**/*',async route=>{const u=route.request().url();if(/^(data|blob|about):/i.test(u))return route.continue();try{await publicAddress(u);await route.continue();}catch{await route.abort('blockedbyclient');}});page=await context.newPage();context.on('page',p=>{if(p!==page)void p.close();});}
async function snapshot(){generation++;references.clear();const elements=[];const deadline=Date.now()+12000;const candidates=page.locator('a[href],button,input:not([type=hidden]),textarea,select,[role=button],[role=link]');let count=0;try{count=Math.min(await candidates.count(),300);}catch{count=0;}
  // A page that is still re-rendering (a search just navigated, a menu just closed) detaches elements mid-read. One vanished element must never fail the whole reading, and nothing here may wait the default 30 s.
  for(let i=0;i<count&&Date.now()<deadline;i++){try{const locator=candidates.nth(i);if(!await locator.isVisible())continue;const handle=await locator.elementHandle({timeout:1500});if(!handle)continue;const item=await handle.evaluate(el=>({tag:el.tagName.toLowerCase(),role:el.getAttribute('role'),name:el.getAttribute('aria-label')||el.getAttribute('placeholder')||el.innerText||el.getAttribute('name')||'',type:el.getAttribute('type')}));item.name=String(item.name).slice(0,200);const ref=`s${generation}e${i}`;references.set(ref,{locator:handle,identity:item});elements.push({ref,...item});}catch{}}
  let title='',text='';try{title=await page.title();}catch{}try{text=(await page.evaluate(()=>document.body?document.body.innerText:'')).slice(0,30000);}catch{}
  return {url:page.url(),title,text,elements};}
async function run(command){if(command.action==='close'){await browser?.close();browser=context=page=undefined;references.clear();return {closed:true};}await connect();if(command.action==='open')await page.goto(await publicAddress(command.url),{waitUntil:'domcontentloaded',timeout:20000});else if(command.action==='click'||command.action==='fill'){if(page.url()!==command.expected_url)throw new Error('Page changed since inspection');const observed=references.get(command.ref);if(!observed||!await observed.locator.isVisible())throw new Error('Element reference is stale; inspect again');const identity=await observed.locator.evaluate(el=>({tag:el.tagName.toLowerCase(),role:el.getAttribute('role'),name:(el.getAttribute('aria-label')||el.getAttribute('placeholder')||el.innerText||el.getAttribute('name')||'').slice(0,200),type:el.getAttribute('type')}));if(JSON.stringify(identity)!==JSON.stringify(observed.identity))throw new Error('Element changed since inspection');references.clear();if(command.action==='fill'){if(identity.type==='password')throw new Error('Enter passwords directly in the browser');await observed.locator.fill(command.text,{timeout:8000});}else await observed.locator.click({timeout:8000});}else if(command.action!=='snapshot')throw new Error('Unsupported browser action');
  if(command.action!=='snapshot'){await page.waitForLoadState('domcontentloaded',{timeout:6000}).catch(()=>{});await page.waitForTimeout(500);}
  try{return await snapshot();}catch{await page.waitForTimeout(800);return snapshot();}}
const lines=readline.createInterface({input:process.stdin});for await(const line of lines){try{const data=await run(JSON.parse(line));process.stdout.write(JSON.stringify({success:true,status:'completed',message:'Browser action completed.',data,verification:'Owned browser page and visible elements were re-read after the action'})+'\n');}catch(error){process.stdout.write(JSON.stringify({success:false,status:'failed',message:String(error?.message||error).slice(0,500),data:{}})+'\n');}}await browser?.close();
